### PR TITLE
Update .travis.yml so as to support the latest rbx

### PR DESCRIPTION
**Pull request by thejamespinto**
Small contribution for future support

### CODE REVIEW

**Comment by thejamespinto** [comment]
As you may see on TravisCI, rbx and rbx-2 have different major versions

image

image

**Comment by thejamespinto** [comment]
Travis is currently failing but #247 will fix it.

**Comment by sferik** [comment]
Thanks!

**Comment by thejamespinto** [comment]
@sferik thank YOU for taking care of so many gems. You're a real dude <span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_64.png);background-position:50% 77.5%;background-size:4100%" title="100"></span></span>  <span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_64.png);background-position:65% 42.5%;background-size:4100%" title="smiley"></span></span>

**Pull request merged**
