### PR TITLE
Fix encoding error

### LINKED ISSUE #155: Incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
So google in all of its infinite wisdom decides to send back an infinity symbol in the error messages.

```
/Users/warmwaffles/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/oauth2-0.9.2/lib/oauth2/error.rb:21:in `join': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
	from /Users/warmwaffles/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/oauth2-0.9.2/lib/oauth2/error.rb:21:in `initialize'
	from /Users/warmwaffles/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/oauth2-0.9.2/lib/oauth2/client.rb:109:in `new'
	from /Users/warmwaffles/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/oauth2-0.9.2/lib/oauth2/client.rb:109:in `request'
	from /Users/warmwaffles/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/oauth2-0.9.2/lib/oauth2/access_token.rb:107:in `request'
	from /Users/warmwaffles/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/oauth2-0.9.2/lib/oauth2/access_token.rb:114:in `get'
```
**Response in google before fix:**

```json
{
   "error":{
      "errors":[
         {
            "domain":"global",
            "reason":"invalidParameter",
            "message":"Invalid value '0'. Values must be within the range: [1, \xE2\x88\x9E)",
            "locationType":"parameter",
            "location":"start-index"
         }
      ],
      "code":400,
      "message":"Invalid value '0'. Values must be within the range: [1, \xE2\x88\x9E)"
   }
}
```

ruby structure

```ruby
{
  "errors"=>[
    {
      "domain"=>"global", 
      "reason"=>"invalidParameter", 
      "message"=>"Invalid value '0'. Values must be within the range: [1, ∞)", 
      "locationType"=>"parameter", 
      "location"=>"start-index"
    }
  ], 
  "code"=>400, 
  "message"=>"Invalid value '0'. Values must be within the range: [1, ∞)"
}
```

originates from `lib/ruby/gems/2.0.0/gems/oauth2-0.9.2/lib/oauth2/error.rb:21:in 'initialize'`

Proposed solution:

```diff
module OAuth2
  class Error < StandardError
    attr_reader :response, :code, :description

    # standard error values include:
    # :invalid_request, :invalid_client, :invalid_token, :invalid_grant, :unsupported_grant_type, :invalid_scope
    def initialize(response)
      response.error = self
      @response = response

      message = []

      if response.parsed.is_a?(Hash)
        @code = response.parsed['error']
        @description = response.parsed['error_description']
        message << "#{@code}: #{@description}"
      end

-      message << response.body
+      message << response.body.force_encoding("UTF-8")

      super(message.join("\n"))
    end
  end
end
```

**Response from google after fix:**

```json
{
   "error":{
      "errors":[
         {
            "domain":"global",
            "reason":"invalidParameter",
            "message":"Invalid value '0'. Values must be within the range: [1, ∞)",
            "locationType":"parameter",
            "location":"start-index"
         }
      ],
      "code":400,
      "message":"Invalid value '0'. Values must be within the range: [1, ∞)"
   }
}
```

ruby structure:

```ruby
{
  "errors" => [
    {
      "domain"=>"global",
      "reason"=>"invalidParameter",
      "message"=>"Invalid value '0'. Values must be within the range: [1, ∞)",
      "locationType"=>"parameter",
      "location"=>"start-index"
    }
  ], 
  "code"=>400, 
  "message"=>"Invalid value '0'. Values must be within the range: [1, ∞)"
}
```

I tried to be as thorough as possible. I don't know what this means in regards to breaking anything. I just ran this test with `bundle open`

### PR DESCRIPTION
**Pull request by Motoshi-Nishihira**
I want to fix #155 

It will occur when Content-Type is `application/json` and response.body's includes non ascii characters.
I think the correct encoding is dependent on the script encoding(`__ENCODING__`).

### CODE REVIEW

**Comment by sferik** [comment]
Thanks!

**Comment by sferik** [comment]
@Motoshi-Nishihira This patch appears to have broken the build on Ruby 1.8.7 and Ruby 1.9.3, which are still [supported](https://github.com/intridea/oauth2#supported-ruby-versions).

Can you please look into this and submit a fix? https://travis-ci.org/intridea/oauth2/builds/129654332

Thank you.

**Comment by JoshCheek** [comment]
I've hit this before and just rolled with UTF-8, but its possible that the file's encoding is a better choice. You should be able to get that by making a new string and checking its encoding:

```ruby
# encoding: utf-8

__ENCODING__  # => #<Encoding:UTF-8>
"".encoding   # => #<Encoding:UTF-8>
```


```ruby
# encoding: us-ascii

__ENCODING__  # => #<Encoding:US-ASCII>
"".encoding   # => #<Encoding:US-ASCII>
```

You should also handle the case where the original string wasn't UTF8, and forcing its encoding leads to invalid UTF8. [Here](https://github.com/JoshCheek/seeing_is_believing/commit/adaccb42c9895aedddb2b9d5e7292803ccd4114e)  are some notes and tests from when I had this issue (aside, has anyone checked all the headers to make sure that the encoding isn't provided somewhere? The original issue didn't give reproduction instructions or provide the headers)

**Comment by JoshCheek** [comment]
Probably want to explicitly look into [this](https://travis-ci.org/intridea/oauth2/jobs/129654334#L195) failure, too.

**Comment by Motoshi-Nishihira** [comment]
Sorry for breaking the build.
I fixied it.

**Pull request merged**
