### PR TITLE
Enable rack 2.0 and test against rack master on travis

### PR DESCRIPTION
**Pull request by matthewrudy**
Copied the approach from [omniauth](https://github.com/intridea/omniauth)

### CODE REVIEW

**Comment by matthewrudy** [comment]
BTW: travis is pretty broken

**Comment by matthewrudy** [comment]
I added a separate PR to fix travis
https://github.com/intridea/oauth2/pull/227

I can rebase this one on top of that to make it easier to merge

**Comment by tosie** [comment]
+1 after merging #227

**Comment by prathamesh-sonpatki** [comment]
Looking forward to this change for Rails5/Rack2 compatibility.

**Pull request closed without merging**
