### PR TITLE
Test support for rack 2.0 on Travis

### PR DESCRIPTION
**Pull request by pschambacher**
@sferik 

Hi!

This gem is on our path to get our gems compatible with Rails 5.0.0.beta1. I noticed that you unlocked the hard dependency on `rack` but it wasn't exactly tested yet. This should do.

I also unlocked the dependency on jwt since it's only for ruby 1.8.

Would you mind releasing a new version, at least alpha/beta, so we can bundle with rails 5 and this gem?

### CODE REVIEW

**Comment by shinnn** [comment]
:+1:

**Comment by pschambacher** [comment]
:eyes: @sferik ?

**Comment by sferik** [comment]
I already released the change that allows `rack` version 2 and relaxed the `jwt` dependency in the gemspec in `master`. Does Rails require a newer version of `jwt`?

**Comment by pschambacher** [comment]
It doesn't. This was just to get the tests running on both versions to be sure because the test suite is only running rack 1.x at the moment.

**Comment by sferik** [comment]
Closed by https://github.com/intridea/oauth2/commit/22d40c7045224f604c1e4224f5e568a4c7be858b.

**Pull request closed without merging**
