### PR TITLE
Restrict rake to < 11.0 for compatibility with ruby18

### PR DESCRIPTION
**Pull request by JoshCheek**
Example of the issue: https://travis-ci.org/intridea/oauth2/jobs/122118341

### CODE REVIEW

**Comment by thejamespinto** [comment]
@JoshCheek thank you for this, I made a PR to update something on Travis and I was wondering how come I had messed up with 1.8 😅

**Comment by thejamespinto** [comment]
@sferik please merge this one...

**Comment by brycejohnston** [comment]
👍

**Comment by sferik** [comment]
Thanks Josh!

**Pull request merged**
