### PR TITLE
Start keeping a change log.

### LINKED ISSUE #208: Change log
Need any help putting together a [change log](http://keepachangelog.com) for this project? 

Just for the sake of documenting the `oauth_token` => `access_token` type changes. Just had a ton of fun dealing with that on an old app.

### PR DESCRIPTION
**Pull request by olivierlacan**
Getting the ball rolling with the latest release. We can work backwards later but hopefully
people can start updating the change log when making a release from now on.

Looks like this rendered: 

image

Fixes #208.

### CODE REVIEW

**Comment by swrobel** [comment]
The wiki changelog is pretty out of date, and this would be helpful. Why hasn't this been done, @sferik @mbleigh ?

**Comment by sferik** [comment]
@swrobel: @mbleigh and I made an [intentional](https://twitter.com/sferik/status/56274138049949697) [decision](https://github.com/intridea/oauth2/commit/5d9c925aeaa29d3017e8500a56305783ce254663) to move the change log from a file to a wiki so that it would be easy for anyone to update. If you would like to update the changelog, you are free to do so.

@olivierlacan I read the link you posted above but I couldn’t find the part where it specifically addresses why a `CHANGELOG` file is better than a wiki. Maybe you could point that out or quote it here?

**Comment by swrobel** [comment]
@sferik I suppose the proof is in the pudding. Your wiki experiment failed. No one is updating it. Convention dictates that a CHANGELOG lives in a file...

**Comment by olivierlacan** [comment]
I wouldn't rub it in as hard, but yes, a GitHub Wiki isn't portable. It doesn't live with the repo, it's a side-dish that is unlikely to be checked by people perusing or contributing to the project. That's why you put the following in the repo's root: 
- README
- CHANGELOG
- LICENSE
- CONTRIBUTING

Because you want people to take note of them. I'll definitely try to ad these remarks to keepachangelog.com.

**Comment by sferik** [comment]
I’m happy to merge this as long as it doesn’t imply an obligation to maintain it. 😜

**Comment by olivierlacan** [comment]
@sferik I really thing everybody should be involved in maintaining it. This is a pretty crucial part of a lot of Ruby app's infrastructure. ;-)

**Comment by swrobel** [comment]
@olivierlacan agreed! The best part about having it in a file is that you can submit changes to the changelog (say that 5 times fast) in a PR. With the Wiki, when do you update it? Presumably you want to when you submit your PR, but it hasn't been merged/tagged for release yet. By the time it's been merged, you've probably forgotten. This process is much smoother.

**Comment by sferik** [comment]
If one of you wants to migrate the wiki into the `CHANGELOG` document and then delete the wiki, I’d be fine with that. There should only be one canonical change log, not two.

Also, if you’re looking to add some prose to those old versions, you can revive it from [this commit](https://github.com/intridea/oauth2/commit/02ee1506f5bb60abd8aad6cc84c81119afb3412e).

**Pull request merged**
