### PR TITLE
Feature/rails 5 compaptibility

### PR DESCRIPTION
**Pull request by tsubery**
Hi, 

I wanted to try out rails 5 beta which requirese at least rack 2.x.
In order to configure get the build passing on travis I had to a few minor changes.
* Limit addressable and JWT gems as they dropped mri1.8.7 support in their latest versions. You might want to consider dropping 1.8.7 support for oauth2 gem too.
* Accepted some style changes offered by latest rubocop and had to disable AbcSize metric to avoid substantial code refactoring in for this PR.
* Skip rubocop on rubinius as it caused the interpreter to crash on travis after running all inspections. As far as I can tell the crash has nothing to do with oauth2 code. Seems to me running rubocop only on MRI is going to make the build faster while giving the same information.

### CODE REVIEW

**Comment by lmmendes** [comment]
:+1:  for the merge! 

Just tested and fixes issues with the latest versions rails (5) and omniauth (master)  that where unable to solve gem dependencies because rails5 actionpack requires rack > 2.0

**Comment by tsubery** [comment]
I suspect the build passes for master just because the gems are cached on travis. When I built it from scratch on my fork it failed. To make the build pass I had to make these changes @https://github.com/tsubery/oauth2/commit/0a50e3b384472051e5466344f3b5bfa7fd25e072.

As you can see, jwt and addressable dropped 1.8.7 support:
https://github.com/jwt/ruby-jwt/commit/332b28184afeb948f9a66d270e6e45df4ce58c86
https://github.com/sporkmonger/addressable/commit/78221c846810b5f8b35096939a9c0a4afbac4433

**Comment by oliverzeyen** [comment]
:+1:  for at least a rails 5 compatible branch

**Comment by sferik** [comment]
Closed by https://github.com/intridea/oauth2/commit/22d40c7045224f604c1e4224f5e568a4c7be858b.

**Pull request closed without merging**
